### ISSUE TITLE
Broken with 0.8.22.9331

### ISSUE THREAD

**Issue by TheRealSTaff** [Acceyuriko/DSPYurikoPlugin#1]
Throws error 
![grafik](https://user-images.githubusercontent.com/19491921/139511822-b1cffa02-d339-4ba7-aa56-bebc973a3e1e.png)
on startup. 
If I disable the mod, the startup error disappears, but 
![grafik](https://user-images.githubusercontent.com/19491921/139511826-6f5825d5-771f-47a4-8df1-4d40514a70d7.png)
appears in game.

**Comment by Acceyuriko** [comment]
> Throws error ![grafik](https://user-images.githubusercontent.com/19491921/139511822-b1cffa02-d339-4ba7-aa56-bebc973a3e1e.png) on startup. If I disable the mod, the startup error disappears, but ![grafik](https://user-images.githubusercontent.com/19491921/139511826-6f5825d5-771f-47a4-8df1-4d40514a70d7.png) appears in game.

OK. it's fixed now.

**Comment by RobTuckfield** [comment]
Seems like a similar issue:

![image](https://user-images.githubusercontent.com/49856780/142513073-ec36e7da-aebe-4b22-8887-064a673da969.png)

**Comment by Acceyuriko** [comment]
> Seems like a similar issue:
> 
> ![image](https://user-images.githubusercontent.com/49856780/142513073-ec36e7da-aebe-4b22-8887-064a673da969.png)

OK. I will fix it on the weekend.

**Comment by TheRealSTaff** [comment]
Thanks for the quick fixes.
The ingame error doesn't appear this time if you disable the mod, so no hurries.

**Comment by Acceyuriko** [comment]
It's fixed now.
