### ISSUE TITLE
Not working on 0.8.23.9989

### ISSUE THREAD

**Issue by MusicalPulse** [Acceyuriko/DSPYurikoPlugin#2]
My save file had achievements disabled on a new game for some reason. Tried this plugin and it still doesn't work. Is it just me or not updated for latest version?

**Comment by Acceyuriko** [comment]
I will check out it. Please wait some days.

**Comment by Acceyuriko** [comment]
I tried it and in this version I am ok. May be caused by conflicts with other plugins.

**Comment by MusicalPulse** [comment]
I dont have any other mods. Don't know what is wrong :(
Thanks for checking.
