### ISSUE TITLE
版本更新后报错 0.9.24.11192

### ISSUE THREAD

**Issue by xcgx** [Acceyuriko/DSPYurikoPlugin#3]
![image](https://user-images.githubusercontent.com/36234354/150478613-d046f6b8-a9b0-4fa1-9a35-b545aab30bc2.png)

**Comment by Acceyuriko** [comment]
垃圾箱的方法坏了，晚上看看

**Comment by xcgx** [comment]
InserterComponentPatch 这个也报错啦 都屏蔽后能跑起来

**Comment by Acceyuriko** [comment]
https://github.com/Acceyuriko/DSPYurikoPlugin/releases/tag/v1.0.3

应该改好了
