### ISSUE TITLE
版本0.9.24.11286更新后报错

### ISSUE THREAD

**Issue by dllplay** [Acceyuriko/DSPYurikoPlugin#5]
大佬...更新后报错..无视报错进游戏的话.会发现所有爪子都不能正常工作

**Comment by Acceyuriko** [comment]
喔喔，春节都没看更新，稍等两天。

**Comment by Acceyuriko** [comment]
https://github.com/Acceyuriko/DSPYurikoPlugin/releases/tag/v1.0.4

改好了，试试看

**Comment by dllplay** [comment]
可以了...谢谢大佬..
外加大佬若可以的话能单独更新一下EnableAchievements.dll么..

**Comment by Acceyuriko** [comment]
https://dsp.thunderstore.io/package/Acceyuriko/EnableAchievements/

也整好了
