### ISSUE TITLE
0.9.25.11989 breaks

### ISSUE THREAD

**Issue by petteyg** [Acceyuriko/DSPYurikoPlugin#7]
GameAbnormailtyData error in the update today with https://dsp.thunderstore.io/package/Acceyuriko/EnableAchievements/1.0.4/.

**Comment by Acceyuriko** [comment]
I will try to fixed it this weekend.

**Comment by BigMiaoTCD** [comment]
好哥哥，绕过成就检测是怎么实现的，跟朋友用联机MOD玩会被BAN成就

**Comment by Acceyuriko** [comment]
> 好哥哥，绕过成就检测是怎么实现的，跟朋友用联机MOD玩会被BAN成就

https://github.com/Acceyuriko/DSPYurikoPlugin/blob/master/patch/GameAbnormalityCheck.cs

**Comment by BigMiaoTCD** [comment]
两眼一黑，还是等大佬更新吧

**Comment by RubberDuck1977** [comment]
> GameAbnormailtyData error in the update today with https://dsp.thunderstore.io/package/Acceyuriko/EnableAchievements/1.0.4/.

i have the same issue

**Comment by Acceyuriko** [comment]
it's fixed at #8 .

**Comment by Acceyuriko** [comment]
> 两眼一黑，还是等大佬更新吧

我看源码里成就检测加了一些检查当前游戏是不是自己的游戏的逻辑，看起来多人联机的时候应该只有主机能获得成就。

我试着改了一下，你试试看。

**Comment by BigMiaoTCD** [comment]
感谢修复，关闭问题后收到个提示邮件才看到已经修好了，可惜现在联机的已经被抓去备考没法测试了
